### ISSUE TITLE
[ENTREGA Recuperatorio Objetos]  Felipe Denza

### ISSUE THREAD

**Issue by FelipeDenza** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-FelipeDenza#1]
Emiliano Salvano y Luca Pavón @EmilianoSalvano @Lpavn
Juan Fernandes y Lucas Zheng @juanFdS @zhl27 
Juani Schuhmann y Dante Ortiz @jschuhmann47 @Effloresc3 
Tomás Antonio @T-J-Antonio
Gustavo Crespi y Manuel Torrente @gcrespi @manutorrente

**Comment by JuanFdS** [comment]
Parte A
---

- Faltó limitar entre 1 y 10 el poder innato
- El nombre de la clase va siempre en singular: ObjetosMagicos debería ser ObjetoMagico, lo mismo con Amuletos.
- No era necesario asignar un usuario a los objetos, con que el mago lo tenga es suficiente, además se complicaría si por ejemplo se pueden dar objetos.
- magoDesafiado.tipoMago() rompe el encapsulamiento
- No debería tirar un error si no lo puede derrotar, ya que es un comportamiento esperado
- puntosPorSerVencido no puede ser de consulta y de efecto a la vez: o retorna la cantidad de puntos a restar, o lo resta, pero no ambas.
- Entre tipoAprendiz y tipoVeterano hay repetición de lógica

Parte B
---

- Los puntos al desafiar a otro gremio van al líder, no se reparten entre los miembros.
- Está mal que se distinga entre mago y gremio, menos con un método queEs. La idea es hacerlos polimórficos así se tratan de forma indistinta, y no tengo que preguntarle a cada uno qué es.
- Para obtener el miembro con mayor poder, se puede usar .max(bloque) directamente.
- crearGremio no se usa, debería en el momento que se intenta crear el objeto.

Nota: 7
